# Generated by Django 4.2.1 on 2023-07-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payee_name', models.CharField(max_length=32)),
                ('payee_address', models.CharField(max_length=32)),
                ('payment_amount', models.CharField(max_length=32)),
            ],
        ),
    ]
