# Generated by Django 4.2.2 on 2023-07-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0001_initial'),
        ('order', '0003_order_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipment',
            field=models.ManyToManyField(blank=True, null=True, to='shipment.shipment'),
        ),
    ]
