# Generated by Django 3.2.12 on 2023-07-26 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0001_initial'),
        ('order', '0004_order_shipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipment',
            field=models.ManyToManyField(blank=True, to='shipment.Shipment'),
        ),
    ]
