# Generated by Django 4.2.2 on 2023-07-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.CharField(max_length=32)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=3)),
                ('status', models.CharField(max_length=32)),
            ],
        ),
    ]
